import arcpy

arcpy.env.overwriteOutput = True
# Path must be changed for outside user workspace
arcpy.env.workspace = r"C:\Users\Thoma\Desktop\Lab2Geog656\Habitat_Analysis.gdb"
print(arcpy.env.workspace)
arcpy.Buffer_analysis("majorrds_shp", "majorrds_buf", 2000)
print "The buffer 'majorrds_buf' has been created."

# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# compare_road_buffer.py
# Created on: 2020-06-14 18:47:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

############################################ Exported Road Buffer Model to compare with first script #####################################
# Import arcpy module
import arcpy


# Local variables:
# Paths must be changed for outside user workspace
majorrds_shp = "C:\\Users\\Thoma\\Desktop\\Lab2Geog656\\Habitat_Analysis.gdb\\majorrds_shp"
majorrds_mb_shp = "C:\\Users\\Thoma\\Desktop\\Lab2Geog656\\majorrds_mb.shp"

# Process: Buffer
arcpy.Buffer_analysis(majorrds_shp, majorrds_mb_shp, "2000 Feet", "FULL", "ROUND", "NONE", "", "PLANAR")
print('Buffer Model Analysis Complete')



# Task 2 myBuffer Function
def myBuffer(workspace, inputFC, outputFC, buffDist):
    '''5000 meter buffer'''
    try:
        arcpy.env.workspace = workspace
        arcpy.Buffer_analysis(inputFC, outputFC, buffDist)
        print "The buffer 'futrds_buffer' has been created."
    except Exception as e:
        print(e)

# Task 4 myNewBuffer function
def myNewBuffer(workspace, inputFC, outputFC, buffDist, buffUnits):
    '''2500 Feet Buffer with added parameters'''
    try:
        if buffUnits == 'Meters' or buffUnits == 'Feet':
            distanceInput= str(buffDist)
            buffInput = distanceInput + " " + buffUnits
            arcpy.env.workspace = workspace
            arcpy.Buffer_analysis(inputFC, outputFC, buffInput)
            print "The 2500 foot buffer 'futrds_buffer' has been created."
        else:
            print "Error, Invalid units for process!"
    except Exception as e:
        print(e)




################################################################## Task 3 MyBuffer Test Input ##########################################################
work = r"C:\Users\Thoma\Desktop\Lab2Geog656\Habitat_Analysis.gdb" #Path = Your workspace path
inFC, outFC, distance = "futrds", "futrds_buffer", 5000
myBuffer(work, inFC, outFC, distance)

#################################### TASK 5 MyNewBuffer Test Input #####################################################################
work = r"C:\Users\Thoma\Desktop\Lab2Geog656\Habitat_Analysis.gdb" # PATH = Your workspace path
inFC, outFC, distance, units = "futrds", "futrds_feet", 2500, "Feet"
myNewBuffer(work, inFC, outFC, distance, units)











############################################################################### TASK 6 Python Script MyBuffer Tool *Must be tested in ArcMap ###################################################

# arcpy.env.workspace = r"C:\Users\Thoma\Desktop\Lab2Geog656\Habitat_Analysis.gdb"
# distance = arcpy.GetParameterAsText(0)
# output = arcpy.GetParameterAsText(1)

# arcpy.Buffer_analysis("majorrds_shp", output, distance)
# arcpy.AddWarning("The buffer " + output + " has been created.")



############################################ TASK 7 -> Python Script MyNewBuffer Tool *Must be tested in ArcMap  ###################################################################

arcpy.env.workspace = arcpy.GetParameterAsText(0)
inputFeat = arcpy.GetParameterAsText(1)
distance = arcpy.GetParameterAsText(2)
units = arcpy.GetParameterAsText(3)
output = arcpy.GetParameterAsText(4)

# Check whether units are Meters or Feet, throw error if not
if units == 'Meters' or units == 'Feet':
    distanceInput= str(distance)
    buffInput = distanceInput + " " + units
    arcpy.env.workspace 
    arcpy.Buffer_analysis(inputFeat, output, buffInput)
    arcpy.AddWarning( "The {} {} buffer {} has been created.".format(distance,units,output))
else:
    print arcpy.AddError("Error, Invalid units for process!")





